import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { FormationScheduleProvider } from "@/contexts/FormationScheduleContext";
import { AuthProvider } from "@/contexts/AuthContext";
import TaskRedirector from "@/components/TaskRedirector";
import AuthRedirector from "@/components/Auth/AuthRedirector";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PixelPlay",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <FormationScheduleProvider>
            <AuthRedirector />
            <TaskRedirector />
            {children}
          </FormationScheduleProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
